# This is a basic workflow that builds all example applications
name: build all apps CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Install libraries and executables locally and tell gStreamer where
    #env:
    #  GST_PLUGIN_PATH: '$GITHUB_WORKSPACE/local_installs'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out signed-video-framework under $GITHUB_WORKSPACE, so the apps can access it
      - uses: actions/checkout@v2
        with:
          repository: AxisCommunications/signed-video-framework
          path: svf_lib
      - uses: actions/checkout@v2
        with:
          path: svf_apps
      - name: Install meson
        run: python -m pip install meson==0.53.2
      - name: Install ninja
        run: python -m pip install ninja==1.9.0.post1
      - name: Setup meson for the lib
        run: meson --prefix $GITHUB_WORKSPACE/local_installs svf_lib build_lib
      - name: Compile and install lib
        run: meson install -C build_lib
      - name: Run apt-get update
        run: sudo apt-get update --fix-missing
      - name: Install gStreamer from package manager
        # run: sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
        run: sudo add-apt-repository universe && sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
        # run: sudo add-apt-repository universe && sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav
        # run: sudo add-apt-repository universe && sudo apt-get install libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev
      - name: Setup meson for the apps
        run: meson -Dbuild_all_apps=true --prefix $GITHUB_WORKSPACE/local_installs svf_apps build_apps
      - name: Compile the apps
        run: meson install -C build_apps
      - name: Run validator on test-files
        run: |
          $GITHUB_WORKSPACE/local_installs/bin/validator.exe -c h264 svf_apps/test-files/test_h264.mp4
          $GITHUB_WORKSPACE/local_installs/bin/validator.exe -c h264 svf_apps/test-files/signed_test_h264.mp4
          $GITHUB_WORKSPACE/local_installs/bin/validator.exe -c h264 svf_apps/test-files/signed_test_h264_modified_frame_137.mp4
          $GITHUB_WORKSPACE/local_installs/bin/validator.exe -c h265 svf_apps/test-files/test_h265.mp4
          $GITHUB_WORKSPACE/local_installs/bin/validator.exe -c h265 svf_apps/test-files/signed_test_h265.mp4
      - name: Copy test files for signing
        run: cp svf_apps/test-files/test_h26*.mp4 .
      - name: Run signer on test-files
        run: |
          export GST_PLUGIN_PATH=$GITHUB_WORKSPACE/local_installs
          $GITHUB_WORKSPACE/local_installs/bin/signer.exe -c h264 test_h264.mp4
          $GITHUB_WORKSPACE/local_installs/bin/validator.exe -c h264 signed_test_h264.mp4
          $GITHUB_WORKSPACE/local_installs/bin/signer.exe -c h265 test_h265.mp4
          $GITHUB_WORKSPACE/local_installs/bin/validator.exe -c h265 signed_test_h265.mp4
