# This is a basic workflow to help you get started with Actions

name: build all apps CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GST_PLUGIN_PATH: $GITHUB_WORKSPACE/local_installs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out signed-video-framework under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      #  with:
      #    repository: AxisCommunications/signed-video-framework
      #    path: svf_lib
      - uses: actions/checkout@v2
        with:
          path: svf_apps

      # Runs a single command using the runners shell
      - name: Install meson
        run: python -m pip install meson==0.53.2
      - name: Install ninja
        run: python -m pip install ninja==1.9.0.post1
      - name: apt-get update
        run: sudo apt-get update --fix-missing
      - name: Install gStreamer manually
        run: sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
      #- name: Setup meson for the lib
      #  run: meson --prefix $GST_PLUGIN_PATH svf_lib build_lib
      #- name: Compile and install lib
      #  run: meson install -C build_lib
      - name: Setup meson for the apps
        run: meson -Dvalidator=false -Dsigner=false svf_apps build_apps
        #run: meson -Dvalidator=false -Dsigner=false --prefix $GST_PLUGIN_PATH svf_apps build_apps
      - name: Compile the apps
        run: ninja -C build_apps
        #run: meson install -C build_lib

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
